import * as THREE from 'three';
import { human3 } from './human3.js';
import { solidHuman } from './overlap.js';
import { M, TEX, canvasTex, rng, V } from './util.js';
import { box, rbox } from './props.js';
import { sign } from './env.js';
import { shadows } from './shot.js';

// ---------- cast ----------
export const cast9 = {
  // white-and-gold priest hero (our stand-in for the hero in the story)
  priest: (n = 'priest') => { const H = human3({ skin: '#d8a882', hair: '#4a2a14', hairStyle: 'short', beard: true, top: 'robe', topColor: '#e8e0c8', pants: 'slacks', pantsColor: '#c8b88a', shoes: '#5a3a1a', dress: true, eyeColor: '#3a6a8a', bulk: 1.05 }); const st = holyStaff(); st.position.set(0, -0.06, 0.02); st.rotation.x = -0.1; H.J.rHand.group.add(st); H.staff = st; const sash = new THREE.Mesh(new THREE.TorusGeometry(1, 0.025, 6, 30), M.col('#c8a24a', 0.3, 0.8)); sash.scale.set(0.19, 0.14, 1); sash.rotation.x = Math.PI / 2; sash.position.y = -0.06; H.J.spine.add(sash); return solidHuman(H, n); },
  // huge stone-skinned horned boss
  boss: (n = 'boss') => { const H = human3({ skin: '#7a7a82', hairStyle: 'bald', helmet: 'horned', top: 'none', pants: 'loincloth', pantsColor: '#4a3a2a', shoes: '#3a3a40', eyeColor: '#ff5a1a', bulk: 1.7, belly: 0.12, limb: 1.5, height: 1.0, gloves: '#5a5a62' }); H.root.scale.setScalar(1.9); H.J.eyes.forEach((e) => e.traverse((m) => { if (m.isMesh) { m.material = new THREE.MeshStandardMaterial({ color: '#ff6a1a', emissive: '#ff4a00', emissiveIntensity: 2.5 }); } })); H.root.traverse((m) => { if (m.isMesh && m.material && m.material.isMeshPhysicalMaterial && (m.material === H.skinMat || m.material.vertexColors)) { m.material.color.set('#666a72'); m.material.sheen = 0; m.material.roughness = 0.8; } }); return solidHuman(H, n); },
  enemy: (n, col = '#8a2a2a', skin = '#e2b08c') => solidHuman(human3({ skin, hair: '#1a1210', hairStyle: 'short', top: 'longsleeve', topColor: col, pants: 'slacks', pantsColor: '#2a1a1a', shoes: '#1a1a1a', dress: true, eyeColor: '#2a1a10', gloves: '#3a2a1a' }), n),
  dev: (n = 'dev') => solidHuman(human3({ skin: '#eccaa8', hair: '#3a2a1a', hairStyle: 'short', glasses: true, top: 'hoodie', topColor: '#3a3a44', pants: 'jeans', shoes: '#e8e4dc', eyeColor: '#3a5a7a' }), n),
};
export function holyStaff() { const g = new THREE.Group(); const st = new THREE.Mesh(new THREE.CylinderGeometry(0.018, 0.022, 1.3, 10), M.col('#c8a24a', 0.3, 0.8)); st.position.y = -0.25; g.add(st); const ring = new THREE.Mesh(new THREE.TorusGeometry(0.09, 0.015, 8, 28), M.col('#ffd23a', 0.2, 0.9)); ring.position.y = 0.48; g.add(ring); const orb = new THREE.Mesh(new THREE.SphereGeometry(0.05, 16, 12), M.std({ color: '#fff4c8', emissive: '#ffd27a', emissiveIntensity: 1.2 })); orb.position.y = 0.48; g.add(orb); g.userData.orb = orb; return shadows(g); }
// small lane creep: round body, head, little spear
export function creep(col = '#3aaa5a') { const g = new THREE.Group(); const body = new THREE.Mesh(new THREE.CapsuleGeometry(0.13, 0.16, 6, 12), M.col(col, 0.6)); body.position.y = 0.32; g.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(0.1, 14, 10), M.col(col, 0.5)); head.position.y = 0.6; g.add(head); for (const s of [-1, 1]) { const e = new THREE.Mesh(new THREE.SphereGeometry(0.018, 8, 6), M.emis('#ffffff', 1.5)); e.position.set(0.035 * s, 0.62, 0.085); g.add(e); } for (const s of [-1, 1]) { const l = new THREE.Mesh(new THREE.CapsuleGeometry(0.04, 0.12, 4, 8), M.col('#3a3a40', 0.6)); l.position.set(0.06 * s, 0.1, 0); g.add(l); } const sp = new THREE.Mesh(new THREE.CylinderGeometry(0.01, 0.01, 0.6, 6), M.col('#6a4a2a', 0.6)); sp.position.set(0.16, 0.42, 0.05); sp.rotation.x = 0.4; g.add(sp); const tip = new THREE.Mesh(new THREE.ConeGeometry(0.025, 0.08, 6), M.col('#c8c8cc', 0.3, 0.9)); tip.position.set(0.16, 0.7, 0.17); tip.rotation.x = 0.4; g.add(tip); return shadows(g); }
// neutral beast for the persuasion demo
export function wolf() { const g = new THREE.Group(); const m = M.col('#6a5a4a', 0.8); const body = new THREE.Mesh(new THREE.CapsuleGeometry(0.16, 0.45, 6, 12), m); body.rotation.z = Math.PI / 2; body.position.y = 0.42; g.add(body); const head = new THREE.Mesh(new THREE.SphereGeometry(0.14, 14, 10), m); head.scale.set(0.9, 0.9, 1.3); head.position.set(0, 0.55, 0); const hg = new THREE.Group(); hg.position.set(0.38, 0, 0); hg.add(head); const snout = new THREE.Mesh(new THREE.ConeGeometry(0.07, 0.18, 10), m); snout.rotation.z = -Math.PI / 2; snout.position.set(0.14, 0.52, 0); hg.add(snout); for (const s of [-1, 1]) { const ear = new THREE.Mesh(new THREE.ConeGeometry(0.04, 0.1, 6), m); ear.position.set(-0.02, 0.68, 0.06 * s); hg.add(ear); const eye = new THREE.Mesh(new THREE.SphereGeometry(0.018, 8, 6), M.emis('#ffd23a', 1.5)); eye.position.set(0.08, 0.58, 0.055 * s); hg.add(eye); } g.add(hg); for (const x of [-0.22, 0.22]) for (const z of [-0.09, 0.09]) { const l = new THREE.Mesh(new THREE.CapsuleGeometry(0.04, 0.25, 4, 8), m); l.position.set(x, 0.17, z); g.add(l); } const tail = new THREE.Mesh(new THREE.CapsuleGeometry(0.035, 0.25, 4, 8), m); tail.rotation.z = -0.9; tail.position.set(-0.42, 0.5, 0); g.add(tail); g.userData.head = hg; return shadows(g); }
// stone tower with a glowing crystal
export function tower9(col = '#3aaa5a') { const g = new THREE.Group(); const st = M.std({ map: TEX.concrete([1, 2], '#8a8478'), roughness: 0.85 }); const base = new THREE.Mesh(new THREE.CylinderGeometry(0.55, 0.7, 0.4, 10), st); base.position.y = 0.2; g.add(base); const sh = new THREE.Mesh(new THREE.CylinderGeometry(0.4, 0.5, 2.2, 10), st); sh.position.y = 1.5; g.add(sh); for (let i = 0; i < 8; i++) { const a = i / 8 * Math.PI * 2; box(0.16, 0.2, 0.16, st, Math.cos(a) * 0.42, 2.7, Math.sin(a) * 0.42, g); } const top = new THREE.Mesh(new THREE.CylinderGeometry(0.5, 0.45, 0.12, 10), st); top.position.y = 2.6; g.add(top); const cr = new THREE.Mesh(new THREE.OctahedronGeometry(0.22, 0), M.std({ color: col, emissive: col, emissiveIntensity: 0.9, roughness: 0.2 })); cr.scale.y = 1.6; cr.position.y = 3.15; g.add(cr); g.userData.cr = cr; return shadows(g); }
// battlefield: grass with a dirt lane along z, trees and rocks at the sides
export function battlefield(scene, { night = false } = {}) {
  scene.background = new THREE.Color(night ? '#0c1018' : '#8ab8e0'); scene.fog = new THREE.Fog(night ? '#0c1018' : '#a8c8e4', 14, 45);
  const tex = canvasTex('bf9', 1024, 1024, (c, w, h) => { c.fillStyle = '#4a7a34'; c.fillRect(0, 0, w, h); const r = rng(4); for (let i = 0; i < 3000; i++) { c.fillStyle = r() > 0.5 ? '#3e6a2c' : '#5a8a3e'; c.fillRect(r() * w, r() * h, 8, 8); } const gr = c.createLinearGradient(w * 0.35, 0, w * 0.65, 0); gr.addColorStop(0, 'rgba(160,130,90,0)'); gr.addColorStop(0.2, '#a8865a'); gr.addColorStop(0.8, '#a8865a'); gr.addColorStop(1, 'rgba(160,130,90,0)'); c.fillStyle = gr; c.fillRect(w * 0.35, 0, w * 0.3, h); for (let i = 0; i < 500; i++) { c.fillStyle = r() > 0.5 ? '#98784e' : '#b8966a'; c.fillRect(w * 0.4 + r() * w * 0.2, r() * h, 6, 6); } }, { repeat: [1, 1] });
  const g = new THREE.Mesh(new THREE.PlaneGeometry(30, 30), M.std({ map: tex, roughness: 0.95 })); g.rotation.x = -Math.PI / 2; g.receiveShadow = true; scene.add(g);
  scene.add(new THREE.HemisphereLight(night ? '#8a9aff' : '#e8f2ff', '#4a5a2a', night ? 0.5 : 0.85));
  const sun = new THREE.DirectionalLight(night ? '#aab8ff' : '#fff0d8', night ? 1.2 : 2.6); sun.position.set(-6, 10, 6); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); Object.assign(sun.shadow.camera, { left: -10, right: 10, top: 10, bottom: -10 }); sun.shadow.bias = -0.0006; scene.add(sun);
  const r = rng(9); const treeG = new THREE.ConeGeometry(0.6, 1.8, 7), trunkG = new THREE.CylinderGeometry(0.1, 0.12, 0.5, 6);
  const trees = new THREE.InstancedMesh(treeG, M.col('#2a5a2a', 0.8), 60), trunks = new THREE.InstancedMesh(trunkG, M.col('#4a3a2a', 0.8), 60); const m4 = new THREE.Matrix4(); let n = 0;
  while (n < 60) { const side = n % 2 ? 1 : -1; const x = side * (3.4 + r() * 8), z = -14 + r() * 26; const s = 0.8 + r() * 0.6; trees.setMatrixAt(n, m4.makeScale(s, s, s).setPosition(x, 1.15 * s, z)); trunks.setMatrixAt(n, m4.makeScale(s, s, s).setPosition(x, 0.25 * s, z)); n++; }
  trees.castShadow = trunks.castShadow = true; scene.add(trees, trunks);
  return { sun };
}
// boss pit: sunken rocky arena ringed by boulders
export function pit(scene) {
  scene.background = new THREE.Color('#0a0c10'); scene.fog = new THREE.Fog('#0a0c10', 8, 26);
  const fl = new THREE.Mesh(new THREE.CircleGeometry(4, 48), M.std({ map: TEX.concrete([3, 3], '#6a6258'), roughness: 0.95 })); fl.rotation.x = -Math.PI / 2; fl.receiveShadow = true; scene.add(fl);
  const r = rng(6); for (let i = 0; i < 22; i++) { const a = i / 22 * Math.PI * 2 + r() * 0.1; if (Math.abs(a - Math.PI / 2) < 0.45) continue; const rk = new THREE.Mesh(new THREE.DodecahedronGeometry(0.8 + r() * 0.6, 0), M.col(['#5a544c', '#4a463e', '#6a6258'][i % 3], 0.9)); rk.position.set(Math.cos(a) * 4.2, 0.4 + r() * 0.6, Math.sin(a) * 4.2); rk.rotation.set(r() * 3, r() * 3, r() * 3); rk.scale.y = 1.3 + r() * 0.8; rk.castShadow = true; rk.receiveShadow = true; scene.add(rk); }
  for (let i = 0; i < 6; i++) { const b = new THREE.Mesh(new THREE.SphereGeometry(0.06 + r() * 0.04, 8, 6), M.col('#e8e0d0', 0.6)); b.scale.set(2, 0.5, 0.6); b.position.set(-2 + r() * 4, 0.03, -2 + r() * 2); b.rotation.y = r() * 3; scene.add(b); }
  scene.add(new THREE.HemisphereLight('#8a90b0', '#2a2018', 0.35));
  const key = new THREE.SpotLight('#ffd8a8', 40, 14, 0.7, 0.6, 1.2); key.position.set(1.5, 6.5, 3.5); key.target.position.set(0, 1, -0.5); key.castShadow = true; key.shadow.mapSize.set(2048, 2048); key.shadow.bias = -0.0006; scene.add(key, key.target);
  const torch = new THREE.PointLight('#ff8a3a', 10, 8, 1.6); torch.position.set(-2.5, 2.2, -1.5); scene.add(torch);
}
export function holyBeam() { const m = new THREE.Mesh(new THREE.CylinderGeometry(0.06, 0.06, 1, 12, 1, true), new THREE.MeshBasicMaterial({ color: '#ffe8a0', transparent: true, opacity: 0.8, blending: THREE.AdditiveBlending, depthWrite: false })); return m; }
export function halo(r = 0.6) { const h = new THREE.Mesh(new THREE.TorusGeometry(r, 0.03, 8, 40), new THREE.MeshBasicMaterial({ color: '#ffe08a', transparent: true, opacity: 0.85, blending: THREE.AdditiveBlending, depthWrite: false })); h.rotation.x = Math.PI / 2; return h; }
export { V };
